export const ErrorCodes = {
  // URL Validation
  INVALID_REPOSITORY_URL: 'INVALID_REPOSITORY_URL',
  MISSING_OWNER: 'MISSING_OWNER',
  MISSING_REPOSITORY: 'MISSING_REPOSITORY',
  NON_GITHUB_URL: 'NON_GITHUB_URL',

  // GitHub API
  REPOSITORY_NOT_FOUND: 'REPOSITORY_NOT_FOUND',
  PRIVATE_REPOSITORY: 'PRIVATE_REPOSITORY',
  GITHUB_RATE_LIMITED: 'GITHUB_RATE_LIMITED',
  GITHUB_UNAVAILABLE: 'GITHUB_UNAVAILABLE',
  GITHUB_API_ERROR: 'GITHUB_API_ERROR',
  TREE_TOO_LARGE: 'TREE_TOO_LARGE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Analysis
  ANALYSIS_TIMEOUT: 'ANALYSIS_TIMEOUT',
  RIO_VALIDATION_FAILED: 'RIO_VALIDATION_FAILED',
  ANALYSIS_FAILED: 'ANALYSIS_FAILED',

  // Redis
  REDIS_UNAVAILABLE: 'REDIS_UNAVAILABLE',
  CACHE_ERROR: 'CACHE_ERROR',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
};
